### ISSUE TITLE
Method "presets" is undefined

### ISSUE THREAD

**Issue by strarsis** [foray1010/image-process-loader#54]
@foray1010:
In SCSS:
```scss
.test {
  background-image: url('../images/background/outdoor-1.jpg?{preset:background}');
}
````

Build error:
````
Module build failed: ModuleBuildError: Module build failed: Error: Method "presets" is undefined
at Object.keys.reduce [...] image-process-loader/src/lib/processImage.js:8:13)
at Array.reduce (<anonymous>)
````

`webpack.config.js`:
```json
[...]
rules: [
      {
        test: /\.(gif|jpe?g|png|svg|tiff|webp)$/,
        use: [
          {
            loader: 'image-process-loader',
            options: {
              jpeg: {
                progressive: true,
              },
              presets: {
                background: {
                  jpeg: {
                    quality: 100,
                  },
                },
              },
            },
          },
        ],
      },
[...]
}
````
